const express = require('express');
const cors = require('cors');
const dotenv = require('dotenv');
const connectDB = require('./config/db');
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
connectDB();
app.get('/', (req,res) => res.send('FoodScan server'));
app.use('/api/auth', require('./routes/auth'));
app.use('/api/scan', require('./routes/scan'));
app.use('/api/preferences', require('./routes/preferences'));
app.use('/api/scans', require('./routes/scans'));
const PORT = process.env.PORT || 5000;
app.listen(PORT, ()=>console.log('Server running on', PORT));
